import { useEffect, useRef, useState, type FormEvent } from "react";
import { Navigate, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { Archive, Bell, BookOpenCheck, CalendarDays, CheckSquare, ChevronLeft, ClipboardList, FileLock2, Gavel, LayoutDashboard, LogOut, Menu, Scale, Search, Settings, ShieldCheck, UsersRound, X } from "lucide-react";
import { useAuth } from "./AuthContext";
import { api, dateTime, patch, post, type Row } from "./api";
import { Button, ErrorBox, Modal, Spinner } from "./components/UI";
import Dashboard from "./pages/Dashboard";
import Documents from "./pages/Documents";
import { MeetingDetail, MeetingsPage } from "./pages/Meetings";
import { MembersPage, SettingsPage } from "./pages/Organization";
import { AgreementsPage, AuditPage, CasesPage, DecisionsPage, InquiriesPage, TasksPage, TrainingsPage } from "./pages/WorkPages";
import { SecurityPage } from "./pages/Security";
import LegalPage from "./pages/Legal";

function Login(){const {login}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setError("");try{await login(String(fd.get("email")),String(fd.get("password")),String(fd.get("totpCode")||""));}catch(err){setError(err instanceof Error?err.message:"Anmeldung fehlgeschlagen.");setBusy(false);}};return <main className="login-page"><section className="login-brand"><div className="brand-mark large"><Gavel/></div><div><span className="brand-kicker">Sichere Gremienarbeit</span><h1>Gemeinsam<br/>mehr bewegen.</h1><p>Die unabhängige Arbeitsplattform für moderne Betriebsräte – strukturiert, nachvollziehbar und in Ihrer Hand.</p></div><div className="login-trust"><span><ShieldCheck/>Lokale Datenhoheit</span><span><FileLock2/>Verschlüsselte Ablage</span><span><UsersRound/>Rollen & Gremien</span></div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><div className="mobile-brand"><Gavel/>BR Manager</div><span className="eyebrow">Willkommen zurück</span><h2>Beim Gremium anmelden</h2><p>Nutzen Sie Ihren persönlichen, vertraulichen Zugang.</p>{error&&<ErrorBox message={error}/>}<label><span>E-Mail-Adresse</span><input name="email" type="email" autoComplete="username" required autoFocus placeholder="name@unternehmen.de"/></label><label><span>Passwort</span><input name="password" type="password" autoComplete="current-password" required placeholder="••••••••••••"/></label><label><span>Zwei-Faktor-Code <small>(falls aktiviert)</small></span><input name="totpCode" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="123456"/></label><button className="button primary login-button" disabled={busy}>{busy?"Anmeldung läuft …":"Sicher anmelden"}</button><small>Dieser Dienst verwendet ausschließlich technisch notwendige Cookies.</small></form></section></main>}

const nav=[
  ["Übersicht","/",LayoutDashboard],["Sitzungen","/sitzungen",CalendarDays],["Vorgänge","/vorgaenge",ClipboardList],["Beschlüsse","/beschluesse",Gavel],["Aufgaben","/aufgaben",CheckSquare],["Dokumente","/dokumente",FileLock2],["Mitarbeiteranfragen","/anfragen",Bell],["Vereinbarungen","/vereinbarungen",Archive],["Rechtswissen","/rechtswissen",Scale],["Mitglieder & Ausschüsse","/gremium",UsersRound],["Seminare","/seminare",BookOpenCheck]
] as const;

function SearchBox(){const [query,setQuery]=useState(""),[results,setResults]=useState<Row[]>([]),navigate=useNavigate(),timer=useRef<number|undefined>(undefined);const change=(value:string)=>{setQuery(value);window.clearTimeout(timer.current);if(value.length<2){setResults([]);return;}timer.current=window.setTimeout(()=>{api<{items:Row[]}>(`/search?q=${encodeURIComponent(value)}`).then(d=>setResults(d.items)).catch(()=>setResults([]));},250);};return <div className="global-search"><Search/><input placeholder="Vorgänge, Dokumente oder Rechtsthemen suchen …" value={query} onChange={e=>change(e.target.value)}/>{results.length>0&&<div className="search-results">{results.map(r=><button key={`${r.type}-${String(r.id)}`} onClick={()=>{navigate(String(r.url));setQuery("");setResults([]);}}><span>{r.type}</span><strong>{r.reference&&`${r.reference} · `}{r.title}</strong></button>)}</div>}</div>}

function NotificationCenter(){const [open,setOpen]=useState(false),[items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(false),container=useRef<HTMLDivElement>(null),navigate=useNavigate();const load=async()=>{setLoading(true);try{const data=await api<{items:Row[]}>("/notifications");setItems(data.items);}finally{setLoading(false);}};useEffect(()=>{void load();const close=(event:MouseEvent)=>{if(container.current&&!container.current.contains(event.target as Node))setOpen(false);};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[]);const unread=items.filter(item=>!item.read_at).length;return <div className="notification-center" ref={container}><button className="notification-button" title="Benachrichtigungen" onClick={()=>{const next=!open;setOpen(next);if(next)void load();}}><Bell/>{unread>0&&<span/>}</button>{open&&<div className="notification-popover"><header><div><strong>Benachrichtigungen</strong><span>{unread} ungelesen</span></div></header><div>{loading&&<Spinner/>}{!loading&&!items.length&&<div className="notification-empty"><Bell/><strong>Alles im Blick</strong><span>Keine neuen Benachrichtigungen.</span></div>}{items.map(item=><button className={item.read_at?"":"unread"} key={String(item.id)} onClick={async()=>{if(!item.read_at)await patch(`/notifications/${item.id}/read`,{});if(item.link)navigate(String(item.link));else await load();setOpen(false);}}><i/><div><strong>{item.title}</strong><span>{item.body}</span><time>{dateTime(item.created_at)}</time></div></button>)}</div></div>}</div>}

function PasswordChange(){const {user,refresh}=useAuth(),[open,setOpen]=useState(Boolean(user?.mustChangePassword)),[error,setError]=useState("");useEffect(()=>setOpen(Boolean(user?.mustChangePassword)),[user?.mustChangePassword]);return <Modal title="Initialpasswort ändern" open={open} onClose={()=>{if(!user?.mustChangePassword)setOpen(false);}}><form className="entity-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("newPassword")!==f.get("confirm")){setError("Die neuen Passwörter stimmen nicht überein.");return;}try{await post("/auth/change-password",{currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")});await refresh();setOpen(false);}catch(err){setError(err instanceof Error?err.message:"Änderung fehlgeschlagen.");}}}>{error&&<ErrorBox message={error}/>}<p className="form-help">Ersetzen Sie das einmalige Initialpasswort durch ein persönliches Passwort mit mindestens 12 Zeichen.</p><label><span>Aktuelles Passwort</span><input name="currentPassword" type="password" required/></label><label><span>Neues Passwort</span><input name="newPassword" type="password" minLength={12} required/></label><label><span>Neues Passwort wiederholen</span><input name="confirm" type="password" minLength={12} required/></label><footer className="form-actions"><Button type="submit">Passwort ändern</Button></footer></form></Modal>}

function Layout(){const {user,permissions,logout}=useAuth(),[mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),navigate=useNavigate();const canAdmin=permissions?.includes("council:manage");return <div className={`app-shell ${collapsed?"collapsed":""}`}><aside className={`sidebar ${mobile?"mobile-open":""}`}><div className="brand"><span className="brand-mark"><Gavel/></span><div><strong>BR Manager</strong><span>{user?.councilName}</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([name,url,Icon])=><NavLink to={url} end={url==="/"} key={url} onClick={()=>setMobile(false)}><Icon/><span>{name}</span></NavLink>)}</nav><div className="nav-admin"><span>Sicherheit</span><NavLink to="/sicherheit"><ShieldCheck/><b>Anmeldung & 2FA</b></NavLink>{canAdmin&&<><NavLink to="/audit"><ShieldCheck/><b>Audit-Protokoll</b></NavLink><NavLink to="/einstellungen"><Settings/><b>Einstellungen</b></NavLink></>}</div><button className="collapse-button" onClick={()=>setCollapsed(v=>!v)}><ChevronLeft/><span>Navigation einklappen</span></button></aside><div className="app-body"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}><Menu/></button><SearchBox/><div className="top-actions"><NotificationCenter/><button className="user-menu" onClick={()=>navigate("/sicherheit")}><span className="avatar">{user?.firstName[0]}{user?.lastName[0]}</span><div><strong>{user?.firstName} {user?.lastName}</strong><span>{String(user?.role).replaceAll("_"," ")}</span></div></button><button className="icon-button" title="Abmelden" onClick={async()=>{await logout();navigate("/");}}><LogOut/></button></div></header><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/sitzungen" element={<MeetingsPage/>}/><Route path="/sitzungen/:id" element={<MeetingDetail/>}/><Route path="/vorgaenge" element={<CasesPage/>}/><Route path="/beschluesse" element={<DecisionsPage/>}/><Route path="/aufgaben" element={<TasksPage/>}/><Route path="/dokumente" element={<Documents/>}/><Route path="/anfragen" element={<InquiriesPage/>}/><Route path="/vereinbarungen" element={<AgreementsPage/>}/><Route path="/rechtswissen" element={<LegalPage/>}/><Route path="/gremium" element={<MembersPage/>}/><Route path="/seminare" element={<TrainingsPage/>}/><Route path="/sicherheit" element={<SecurityPage/>}/>{canAdmin&&<><Route path="/audit" element={<AuditPage/>}/><Route path="/einstellungen" element={<SettingsPage/>}/></>}<Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div><PasswordChange/>{mobile&&<div className="mobile-overlay" onClick={()=>setMobile(false)}/>}</div>}

export default function App(){const {loading,user}=useAuth();if(loading)return <div className="boot"><div className="brand-mark large"><Gavel/></div><Spinner/></div>;return user?<Layout/>:<Login/>}
