import { useEffect, useRef, useState, type FormEvent } from "react";
import { Navigate, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { Archive, ArrowRight, Bell, BookOpen, BookOpenCheck, CalendarDays, CheckCircle2, CheckSquare, ChevronLeft, ClipboardList, Command, FileLock2, Gavel, LayoutDashboard, ListTodo, LogOut, Menu, Scale, Search, Settings, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { useAuth } from "./AuthContext";
import { api, dateTime, patch, post, type Row } from "./api";
import { Button, ErrorBox, Modal, Spinner } from "./components/UI";
import Dashboard from "./pages/Dashboard";
import Documents from "./pages/Documents";
import { MeetingDetail, MeetingsPage } from "./pages/Meetings";
import { MembersPage, SettingsPage } from "./pages/Organization";
import { AgreementsPage, AuditPage, CasesPage, DecisionsPage, InquiriesPage, TasksPage, TrainingsPage } from "./pages/WorkPages";
import { SecurityPage } from "./pages/Security";
import LegalPage from "./pages/Legal";

function Login(){const {login}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setError("");try{await login(String(fd.get("email")),String(fd.get("password")),String(fd.get("totpCode")||""));}catch(err){setError(err instanceof Error?err.message:"Anmeldung fehlgeschlagen.");setBusy(false);}};return <main className="login-page"><section className="login-brand"><div className="brand-mark large"><Gavel/></div><div><span className="brand-kicker">Sichere Gremienarbeit</span><h1>Gemeinsam<br/>mehr bewegen.</h1><p>Die unabhängige Arbeitsplattform für moderne Betriebsräte – strukturiert, nachvollziehbar und in Ihrer Hand.</p></div><div className="login-trust"><span><ShieldCheck/>Lokale Datenhoheit</span><span><FileLock2/>Verschlüsselte Ablage</span><span><UsersRound/>Rollen & Gremien</span></div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><div className="mobile-brand"><Gavel/>BR Manager</div><span className="eyebrow">Willkommen zurück</span><h2>Beim Gremium anmelden</h2><p>Nutzen Sie Ihren persönlichen, vertraulichen Zugang.</p>{error&&<ErrorBox message={error}/>}<label><span>E-Mail-Adresse</span><input name="email" type="email" autoComplete="username" required autoFocus placeholder="name@unternehmen.de"/></label><label><span>Passwort</span><input name="password" type="password" autoComplete="current-password" required placeholder="••••••••••••"/></label><label><span>Zwei-Faktor-Code <small>(falls aktiviert)</small></span><input name="totpCode" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="123456"/></label><button className="button primary login-button" disabled={busy}>{busy?"Anmeldung läuft …":"Sicher anmelden"}</button><small>Dieser Dienst verwendet ausschließlich technisch notwendige Cookies.</small></form></section></main>}

const nav=[
  ["Übersicht","/",LayoutDashboard],["Sitzungen","/sitzungen",CalendarDays],["Vorgänge","/vorgaenge",ClipboardList],["Beschlüsse","/beschluesse",Gavel],["Aufgaben","/aufgaben",CheckSquare],["Dokumente","/dokumente",FileLock2],["Mitarbeiteranfragen","/anfragen",Bell],["Vereinbarungen","/vereinbarungen",Archive],["Rechtswissen","/rechtswissen",Scale],["Mitglieder & Ausschüsse","/gremium",UsersRound],["Seminare","/seminare",BookOpenCheck]
] as const;

const quickCommands=[
  {title:"Geführten Fall starten",description:"Standardverfahren in Alltagssprache auswählen",url:"/vorgaenge?assistant=1",icon:Sparkles},
  {title:"Neue Aufgabe anlegen",description:"Arbeitsauftrag und Zuständigkeit erfassen",url:"/aufgaben?new=1",icon:ListTodo},
  {title:"Mitarbeiteranfrage aufnehmen",description:"Vertrauliches Anliegen dokumentieren",url:"/anfragen?new=1",icon:Bell},
  {title:"Rechtswissen öffnen",description:"BetrVG nach einem Thema durchsuchen",url:"/rechtswissen",icon:BookOpen},
] as const;

function CommandCenter(){
  const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<Row[]>([]),[active,setActive]=useState(0),navigate=useNavigate(),input=useRef<HTMLInputElement>(null);
  useEffect(()=>{const keyboard=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(value=>!value);}if(event.key==="Escape")setOpen(false);};document.addEventListener("keydown",keyboard);return()=>document.removeEventListener("keydown",keyboard);},[]);
  useEffect(()=>{if(open)window.setTimeout(()=>input.current?.focus(),30);else{setQuery("");setResults([]);setActive(0);}},[open]);
  useEffect(()=>{if(query.trim().length<2){setResults([]);setActive(0);return;}const timer=window.setTimeout(()=>{api<{items:Row[]}>(`/search?q=${encodeURIComponent(query)}`).then(data=>{setResults(data.items);setActive(0);}).catch(()=>setResults([]));},180);return()=>window.clearTimeout(timer);},[query]);
  const choices=query.trim().length>=2?results:quickCommands.map((item,index)=>({id:`quick-${index}`,title:item.title,type:"Schnellaktion",reference:item.description,url:item.url}));
  const go=(url:unknown)=>{navigate(String(url));setOpen(false);};
  const keyDown=(event:React.KeyboardEvent<HTMLInputElement>)=>{if(event.key==="ArrowDown"&&choices.length){event.preventDefault();setActive(value=>Math.min(value+1,choices.length-1));}if(event.key==="ArrowUp"&&choices.length){event.preventDefault();setActive(value=>Math.max(value-1,0));}if(event.key==="Enter"&&choices[active]){event.preventDefault();go(choices[active].url);}};
  return <><button className="command-trigger" onClick={()=>setOpen(true)}><Search/><span>Alles durchsuchen oder Aktion starten …</span><kbd><Command/>K</kbd></button>{open&&<div className="command-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false);}}><section className="command-palette" role="dialog" aria-modal="true" aria-label="Suchen und Aktionen"><header><Search/><input ref={input} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={keyDown} placeholder="Thema, Aktenzeichen, Aufgabe oder Paragraph …"/><kbd>ESC</kbd></header><div className="command-context"><span>{query.length>=2?"Treffer in allen Modulen":"Schnell starten"}</span><small>↑↓ auswählen · Enter öffnen</small></div><div className="command-results">{choices.map((item,index)=>{const quick=query.trim().length<2?quickCommands[index]:undefined,Icon=quick?.icon||ArrowRight;return <button className={index===active?"active":""} onMouseEnter={()=>setActive(index)} onClick={()=>go(item.url)} key={`${item.type}-${item.id}`}><span><Icon/></span><div><strong>{item.title}</strong><small>{item.reference||item.type}</small></div><b>{item.type}</b><ArrowRight/></button>})}{query.length>=2&&!choices.length&&<div className="command-empty"><Search/><strong>Keine Treffer</strong><span>Versuchen Sie ein allgemeineres Wort oder einen Paragraphen.</span></div>}</div><footer><span><ShieldCheck/>Gremienintern und mandantengetrennt</span><span><Command/>K jederzeit öffnen</span></footer></section></div>}</>;
}

function ToastViewport(){const [toast,setToast]=useState<{id:number;message:string}|null>(null);useEffect(()=>{let timer:number|undefined;const show=(event:Event)=>{const detail=(event as CustomEvent<{message:string}>).detail;const next={id:Date.now(),message:detail.message};setToast(next);window.clearTimeout(timer);timer=window.setTimeout(()=>setToast(current=>current?.id===next.id?null:current),2800);};window.addEventListener("br-manager:toast",show);return()=>{window.removeEventListener("br-manager:toast",show);window.clearTimeout(timer);};},[]);return <div className="toast-viewport" aria-live="polite">{toast&&<div className="toast success"><CheckCircle2/><span>{toast.message}</span><button onClick={()=>setToast(null)} aria-label="Meldung schließen"><X/></button></div>}</div>}

function NotificationCenter(){const [open,setOpen]=useState(false),[items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(false),container=useRef<HTMLDivElement>(null),navigate=useNavigate();const load=async()=>{setLoading(true);try{const data=await api<{items:Row[]}>("/notifications");setItems(data.items);}finally{setLoading(false);}};useEffect(()=>{void load();const close=(event:MouseEvent)=>{if(container.current&&!container.current.contains(event.target as Node))setOpen(false);};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[]);const unread=items.filter(item=>!item.read_at).length;return <div className="notification-center" ref={container}><button className="notification-button" title="Benachrichtigungen" onClick={()=>{const next=!open;setOpen(next);if(next)void load();}}><Bell/>{unread>0&&<span/>}</button>{open&&<div className="notification-popover"><header><div><strong>Benachrichtigungen</strong><span>{unread} ungelesen</span></div></header><div>{loading&&<Spinner/>}{!loading&&!items.length&&<div className="notification-empty"><Bell/><strong>Alles im Blick</strong><span>Keine neuen Benachrichtigungen.</span></div>}{items.map(item=><button className={item.read_at?"":"unread"} key={String(item.id)} onClick={async()=>{if(!item.read_at)await patch(`/notifications/${item.id}/read`,{});if(item.link)navigate(String(item.link));else await load();setOpen(false);}}><i/><div><strong>{item.title}</strong><span>{item.body}</span><time>{dateTime(item.created_at)}</time></div></button>)}</div></div>}</div>}

function PasswordChange(){const {user,refresh}=useAuth(),[open,setOpen]=useState(Boolean(user?.mustChangePassword)),[error,setError]=useState("");useEffect(()=>setOpen(Boolean(user?.mustChangePassword)),[user?.mustChangePassword]);return <Modal title="Initialpasswort ändern" open={open} onClose={()=>{if(!user?.mustChangePassword)setOpen(false);}}><form className="entity-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("newPassword")!==f.get("confirm")){setError("Die neuen Passwörter stimmen nicht überein.");return;}try{await post("/auth/change-password",{currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")});await refresh();setOpen(false);}catch(err){setError(err instanceof Error?err.message:"Änderung fehlgeschlagen.");}}}>{error&&<ErrorBox message={error}/>}<p className="form-help">Ersetzen Sie das einmalige Initialpasswort durch ein persönliches Passwort mit mindestens 12 Zeichen.</p><label><span>Aktuelles Passwort</span><input name="currentPassword" type="password" required/></label><label><span>Neues Passwort</span><input name="newPassword" type="password" minLength={12} required/></label><label><span>Neues Passwort wiederholen</span><input name="confirm" type="password" minLength={12} required/></label><footer className="form-actions"><Button type="submit">Passwort ändern</Button></footer></form></Modal>}

function Layout(){const {user,permissions,logout}=useAuth(),[mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),navigate=useNavigate();const canAdmin=permissions?.includes("council:manage");return <div className={`app-shell ${collapsed?"collapsed":""}`}><a className="skip-link" href="#main-content">Zum Hauptinhalt springen</a><aside className={`sidebar ${mobile?"mobile-open":""}`}><div className="brand"><span className="brand-mark"><Gavel/></span><div><strong>BR Manager</strong><span>{user?.councilName}</span></div><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Navigation schließen"><X/></button></div><nav>{nav.map(([name,url,Icon])=><NavLink to={url} end={url==="/"} key={url} onClick={()=>setMobile(false)}><Icon/><span>{name}</span></NavLink>)}</nav><div className="nav-admin"><span>Sicherheit</span><NavLink to="/sicherheit"><ShieldCheck/><b>Anmeldung & 2FA</b></NavLink>{canAdmin&&<><NavLink to="/audit"><ShieldCheck/><b>Audit-Protokoll</b></NavLink><NavLink to="/einstellungen"><Settings/><b>Einstellungen</b></NavLink></>}</div><button className="collapse-button" onClick={()=>setCollapsed(v=>!v)}><ChevronLeft/><span>Navigation einklappen</span></button></aside><div className="app-body"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)} aria-label="Navigation öffnen"><Menu/></button><CommandCenter/><div className="top-actions"><NotificationCenter/><button className="user-menu" onClick={()=>navigate("/sicherheit")}><span className="avatar">{user?.firstName[0]}{user?.lastName[0]}</span><div><strong>{user?.firstName} {user?.lastName}</strong><span>{String(user?.role).replaceAll("_"," ")}</span></div></button><button className="icon-button" title="Abmelden" onClick={async()=>{await logout();navigate("/");}}><LogOut/></button></div></header><main className="content" id="main-content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/sitzungen" element={<MeetingsPage/>}/><Route path="/sitzungen/:id" element={<MeetingDetail/>}/><Route path="/vorgaenge" element={<CasesPage/>}/><Route path="/beschluesse" element={<DecisionsPage/>}/><Route path="/aufgaben" element={<TasksPage/>}/><Route path="/dokumente" element={<Documents/>}/><Route path="/anfragen" element={<InquiriesPage/>}/><Route path="/vereinbarungen" element={<AgreementsPage/>}/><Route path="/rechtswissen" element={<LegalPage/>}/><Route path="/gremium" element={<MembersPage/>}/><Route path="/seminare" element={<TrainingsPage/>}/><Route path="/sicherheit" element={<SecurityPage/>}/>{canAdmin&&<><Route path="/audit" element={<AuditPage/>}/><Route path="/einstellungen" element={<SettingsPage/>}/></>}<Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div><PasswordChange/><ToastViewport/>{mobile&&<div className="mobile-overlay" onClick={()=>setMobile(false)}/>}</div>}

export default function App(){const {loading,user}=useAuth();if(loading)return <div className="boot"><div className="brand-mark large"><Gavel/></div><Spinner/></div>;return user?<Layout/>:<Login/>}
