import { Router } from "express";
import { randomUUID } from "node:crypto";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { audit } from "../audit.js";
import { permit } from "../auth.js";
import { getDb } from "../database.js";
import { HttpError } from "../http.js";
import { roles, type AuthRequest } from "../types.js";
import { assertOwned } from "../ownership.js";

const router=Router();
const routeParam=(req:AuthRequest,key:string)=>String(req.params[key]);
const optionalId=z.string().uuid().optional().nullable().transform(v=>v||null);

router.get("/members",(req:AuthRequest,res)=>{
  const items=getDb().prepare(`SELECT id,email,first_name,last_name,role,position,phone,active,substitute_rank,last_login_at,created_at FROM users WHERE council_id=? ORDER BY active DESC,last_name,first_name`).all(req.user!.councilId);res.json({items});
});
router.get("/members/:id",(req:AuthRequest,res)=>{const db=getDb(),c=req.user!.councilId,id=routeParam(req,"id"),item=db.prepare(`SELECT id,email,first_name,last_name,first_name||' '||last_name display_name,role,position,phone,active,substitute_rank,last_login_at,created_at,updated_at,two_factor_enabled FROM users WHERE id=? AND council_id=?`).get(id,c);if(!item)throw new HttpError(404,"Mitglied nicht gefunden.");const committees=db.prepare(`SELECT co.id,co.name,co.kind,cm.function FROM committee_members cm JOIN committees co ON co.id=cm.committee_id WHERE cm.user_id=? AND co.council_id=?`).all(id,c),tasks=db.prepare("SELECT id,title,status,due_at FROM tasks WHERE assigned_to=? AND council_id=? AND status<>'erledigt' ORDER BY due_at LIMIT 20").all(id,c),trainings=db.prepare("SELECT id,title,status,starts_at FROM trainings WHERE user_id=? AND council_id=? ORDER BY starts_at DESC LIMIT 20").all(id,c);res.json({item,related:{committees,tasks,trainings}});});
const memberSchema=z.object({email:z.email().max(254),firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),role:z.enum(roles),position:z.string().max(100).optional().default(""),phone:z.string().max(80).optional().default(""),temporaryPassword:z.string().min(12).max(200),substituteRank:z.coerce.number().int().positive().optional().nullable()});
router.post("/members",permit("members:manage"),(req:AuthRequest,res)=>{const d=memberSchema.parse(req.body),id=randomUUID(),db=getDb();db.prepare(`INSERT INTO users (id,council_id,email,password_hash,first_name,last_name,role,position,phone,must_change_password,substitute_rank) VALUES (?,?,?,?,?,?,?,?,?,1,?)`).run(id,req.user!.councilId,d.email.toLowerCase(),bcrypt.hashSync(d.temporaryPassword,12),d.firstName,d.lastName,d.role,d.position,d.phone,d.substituteRank??null);audit(db,req,"created","user",id,{email:d.email,role:d.role});res.status(201).json({id});});
router.patch("/members/:id",permit("members:manage"),(req:AuthRequest,res)=>{const d=memberSchema.omit({temporaryPassword:true}).partial().extend({active:z.boolean().optional(),temporaryPassword:z.string().min(12).max(200).optional().or(z.literal("")).transform(value=>value||undefined)}).parse(req.body),db=getDb();if(!db.prepare("SELECT id FROM users WHERE id=? AND council_id=?").get(routeParam(req,"id"),req.user!.councilId))throw new HttpError(404,"Mitglied nicht gefunden.");if(routeParam(req,"id")===req.user!.id&&d.active===false)throw new HttpError(400,"Das eigene Konto kann nicht deaktiviert werden.");const map:Record<string,string>={email:"email",firstName:"first_name",lastName:"last_name",role:"role",position:"position",phone:"phone",active:"active",substituteRank:"substitute_rank"};const e=Object.entries(d).filter(([k])=>map[k]);if(e.length)db.prepare(`UPDATE users SET ${e.map(([k])=>`${map[k]}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=? AND council_id=?`).run(...e.map(([k,v])=>k==="active"?(v?1:0):v),routeParam(req,"id"),req.user!.councilId);if(d.temporaryPassword){db.prepare("UPDATE users SET password_hash=?,must_change_password=1 WHERE id=?").run(bcrypt.hashSync(d.temporaryPassword,12),routeParam(req,"id"));db.prepare("DELETE FROM sessions WHERE user_id=?").run(routeParam(req,"id"));}audit(db,req,"updated","user",routeParam(req,"id"),{fields:Object.keys(d).filter(key=>d[key as keyof typeof d]!==undefined)});res.status(204).end();});

router.get("/committees",(req:AuthRequest,res)=>{const db=getDb(),items=db.prepare(`SELECT c.*,(SELECT COUNT(*) FROM committee_members cm WHERE cm.committee_id=c.id) member_count FROM committees c WHERE c.council_id=? ORDER BY c.kind,c.name`).all(req.user!.councilId) as Record<string,unknown>[];const members=db.prepare(`SELECT cm.committee_id,cm.user_id,cm.function,u.first_name,u.last_name FROM committee_members cm JOIN committees c ON c.id=cm.committee_id JOIN users u ON u.id=cm.user_id WHERE c.council_id=? ORDER BY u.last_name`).all(req.user!.councilId);res.json({items,members});});
router.get("/committees/:id",(req:AuthRequest,res)=>{const db=getDb(),c=req.user!.councilId,id=routeParam(req,"id"),item=db.prepare("SELECT * FROM committees WHERE id=? AND council_id=?").get(id,c);if(!item)throw new HttpError(404,"Gremium nicht gefunden.");const members=db.prepare(`SELECT cm.user_id,cm.function,u.first_name,u.last_name,u.role,u.position FROM committee_members cm JOIN users u ON u.id=cm.user_id WHERE cm.committee_id=? ORDER BY u.last_name`).all(id),meetings=db.prepare("SELECT id,sequence_no,title,starts_at,status FROM meetings WHERE committee_id=? AND council_id=? ORDER BY starts_at DESC LIMIT 20").all(id,c);res.json({item,related:{members,meetings}});});
const committeeSchema=z.object({name:z.string().trim().min(2).max(160),kind:z.enum(["gremium","ausschuss","arbeitsgruppe","jav","sbv","wahlvorstand"]).optional().default("ausschuss"),description:z.string().max(2000).optional().default("")});
router.post("/committees",permit("council:manage"),(req:AuthRequest,res)=>{const d=committeeSchema.parse(req.body),id=randomUUID(),db=getDb();db.prepare("INSERT INTO committees (id,council_id,name,kind,description) VALUES (?,?,?,?,?)").run(id,req.user!.councilId,d.name,d.kind,d.description);audit(db,req,"created","committee",id,{name:d.name});res.status(201).json({id});});
router.patch("/committees/:id",permit("council:manage"),(req:AuthRequest,res)=>{const d=committeeSchema.partial().parse(req.body),db=getDb(),id=routeParam(req,"id");if(!db.prepare("SELECT id FROM committees WHERE id=? AND council_id=?").get(id,req.user!.councilId))throw new HttpError(404,"Gremium nicht gefunden.");const map:Record<string,string>={name:"name",kind:"kind",description:"description"},entries=Object.entries(d);if(entries.length)db.prepare(`UPDATE committees SET ${entries.map(([key])=>`${map[key]}=?`).join(",")} WHERE id=? AND council_id=?`).run(...entries.map(([,value])=>value),id,req.user!.councilId);audit(db,req,"updated","committee",id,{fields:entries.map(([key])=>key)});res.status(204).end();});
router.put("/committees/:id/members",permit("council:manage"),(req:AuthRequest,res)=>{const d=z.object({members:z.array(z.object({userId:z.string().uuid(),function:z.string().max(100).optional().default("Mitglied")})).max(100)}).parse(req.body),db=getDb();if(!db.prepare("SELECT id FROM committees WHERE id=? AND council_id=?").get(routeParam(req,"id"),req.user!.councilId))throw new HttpError(404,"Gremium nicht gefunden.");db.transaction(()=>{db.prepare("DELETE FROM committee_members WHERE committee_id=?").run(routeParam(req,"id"));const insert=db.prepare("INSERT INTO committee_members (committee_id,user_id,function) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM users WHERE id=? AND council_id=?)");for(const m of d.members)insert.run(routeParam(req,"id"),m.userId,m.function,m.userId,req.user!.councilId);})();audit(db,req,"members_updated","committee",routeParam(req,"id"),{count:d.members.length});res.status(204).end();});

router.get("/trainings",(req:AuthRequest,res)=>{const items=getDb().prepare(`SELECT t.*,u.first_name,u.last_name,d.reference decision_reference FROM trainings t JOIN users u ON u.id=t.user_id LEFT JOIN decisions d ON d.id=t.decision_id WHERE t.council_id=? ORDER BY t.starts_at DESC`).all(req.user!.councilId);res.json({items});});
router.get("/trainings/:id",(req:AuthRequest,res)=>{const db=getDb(),councilId=req.user!.councilId,item=db.prepare(`SELECT t.*,u.first_name,u.last_name,d.reference decision_reference,d.title decision_title FROM trainings t JOIN users u ON u.id=t.user_id LEFT JOIN decisions d ON d.id=t.decision_id WHERE t.id=? AND t.council_id=?`).get(routeParam(req,"id"),councilId) as Record<string,unknown>|undefined;if(!item)throw new HttpError(404,"Schulung nicht gefunden.");const members=db.prepare("SELECT id,first_name,last_name,role,position FROM users WHERE id=? AND council_id=?").all(item.user_id,councilId),decisions=item.decision_id?db.prepare("SELECT id,reference,title,result status,decided_at FROM decisions WHERE id=? AND council_id=?").all(item.decision_id,councilId):[];res.json({item,related:{members,decisions}});});
const trainingSchema=z.object({userId:z.string().uuid(),title:z.string().trim().min(3).max(200),provider:z.string().max(200).optional().default(""),startsAt:z.string().min(10).max(40),endsAt:z.string().min(10).max(40),status:z.enum(["bedarf","beantragt","beschlossen","gebucht","abgeschlossen","abgelehnt"]).optional().default("bedarf"),costEuro:z.coerce.number().min(0).max(1000000).optional().default(0),decisionId:optionalId,notes:z.string().max(5000).optional().default("")});
router.post("/trainings",permit("trainings:write"),(req:AuthRequest,res)=>{const d=trainingSchema.parse(req.body),id=randomUUID(),db=getDb(),councilId=req.user!.councilId;assertOwned(db,councilId,"users",d.userId,"Mitglied");assertOwned(db,councilId,"decisions",d.decisionId,"Entsendebeschluss");db.prepare(`INSERT INTO trainings (id,council_id,user_id,title,provider,starts_at,ends_at,status,cost_cents,decision_id,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,councilId,d.userId,d.title,d.provider,d.startsAt,d.endsAt,d.status,Math.round(d.costEuro*100),d.decisionId,d.notes,req.user!.id);audit(db,req,"created","training",id,{title:d.title});res.status(201).json({id});});
router.patch("/trainings/:id",permit("trainings:write"),(req:AuthRequest,res)=>{const d=trainingSchema.partial().parse(req.body),db=getDb(),id=routeParam(req,"id"),councilId=req.user!.councilId;if(!db.prepare("SELECT id FROM trainings WHERE id=? AND council_id=?").get(id,councilId))throw new HttpError(404,"Schulung nicht gefunden.");assertOwned(db,councilId,"users",d.userId,"Mitglied");assertOwned(db,councilId,"decisions",d.decisionId,"Entsendebeschluss");const map:Record<string,string>={userId:"user_id",title:"title",provider:"provider",startsAt:"starts_at",endsAt:"ends_at",status:"status",costEuro:"cost_cents",decisionId:"decision_id",notes:"notes"},entries=Object.entries(d);if(entries.length)db.prepare(`UPDATE trainings SET ${entries.map(([key])=>`${map[key]}=?`).join(",")} WHERE id=? AND council_id=?`).run(...entries.map(([key,value])=>key==="costEuro"?Math.round(Number(value)*100):value),id,councilId);audit(db,req,"updated","training",id,{fields:entries.map(([key])=>key)});res.status(204).end();});

router.get("/council",(req:AuthRequest,res)=>{const council=getDb().prepare("SELECT * FROM councils WHERE id=?").get(req.user!.councilId);res.json({council});});
router.patch("/council",permit("council:manage"),(req:AuthRequest,res)=>{const d=z.object({name:z.string().trim().min(2).max(200).optional(),companyName:z.string().max(200).optional(),address:z.string().max(1000).optional(),termStart:z.string().max(40).optional().nullable(),termEnd:z.string().max(40).optional().nullable(),meetingNoticeDays:z.coerce.number().int().min(0).max(30).optional()}).parse(req.body),map:Record<string,string>={name:"name",companyName:"company_name",address:"address",termStart:"term_start",termEnd:"term_end",meetingNoticeDays:"meeting_notice_days"},e=Object.entries(d),db=getDb();if(e.length)db.prepare(`UPDATE councils SET ${e.map(([k])=>`${map[k]}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...e.map(([,v])=>v),req.user!.councilId);audit(db,req,"updated","council",req.user!.councilId,{fields:e.map(([k])=>k)});res.status(204).end();});

router.get("/notifications",(req:AuthRequest,res)=>{const items=getDb().prepare("SELECT * FROM notifications WHERE council_id=? AND (user_id IS NULL OR user_id=?) ORDER BY created_at DESC LIMIT 50").all(req.user!.councilId,req.user!.id);res.json({items});});
router.patch("/notifications/:id/read",(req:AuthRequest,res)=>{getDb().prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND council_id=? AND (user_id IS NULL OR user_id=?)").run(routeParam(req,"id"),req.user!.councilId,req.user!.id);res.status(204).end();});
router.get("/audit",permit("audit:read"),(req:AuthRequest,res)=>{const items=getDb().prepare(`SELECT a.*,u.first_name,u.last_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.council_id=? ORDER BY a.created_at DESC LIMIT 500`).all(req.user!.councilId);res.json({items});});

export default router;
