import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, BookOpen, CalendarDays, ClipboardCheck, FileClock, FolderLock, Inbox, Scale, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { api, dateTime, type Row } from "../api";
import { ErrorBox, PageHeader, Panel, Spinner } from "../components/UI";
import { Status } from "../components/Status";
import { useAuth } from "../AuthContext";

interface DashboardData{stats:Record<string,number>;meetings:Row[];deadlines:Row[];activity:Row[]}
export default function Dashboard(){const {user}=useAuth(),[data,setData]=useState<DashboardData|null>(null),[error,setError]=useState("");useEffect(()=>{api<DashboardData>("/dashboard").then(setData).catch(e=>setError(e instanceof Error?e.message:"Fehler"));},[]);if(error)return <ErrorBox message={error}/>;if(!data)return <Spinner/>;const stats=[
  ["Offene Vorgänge",data.stats.openCases,"/vorgaenge",Scale,"teal"],["Fristen ≤ 7 Tage",data.stats.dueSoon,"/vorgaenge",FileClock,"amber"],["Offene Aufgaben",data.stats.openTasks,"/aufgaben",ClipboardCheck,"blue"],["Mitarbeiteranfragen",data.stats.openInquiries,"/anfragen",Inbox,"rose"],["Aktive Vereinbarungen",data.stats.activeAgreements,"/vereinbarungen",FolderLock,"purple"]
] as const;return <><PageHeader eyebrow="Arbeitszentrale" title={`Guten Tag, ${user?.firstName}.`} description="Alle Fristen, Sitzungen und offenen Themen des Gremiums auf einen Blick."/><section className="novice-start"><div><span><Sparkles/></span><div><small>Ohne juristische Vorkenntnisse starten</small><strong>Was ist passiert? Die Software führt Sie Schritt für Schritt.</strong><p>Wählen Sie einen typischen Fall in Alltagssprache. Passende Rechtsgrundlagen, Prüffragen und Aufgaben werden automatisch vorbereitet.</p></div></div><div><Link className="button primary" to="/vorgaenge?assistant=1"><Sparkles/>Fall auswählen</Link><Link className="button secondary" to="/rechtswissen"><BookOpen/>Rechtswissen durchsuchen</Link></div></section><div className="stat-grid">{stats.map(([title,value,url,Icon,tone])=><Link to={url} className={`stat-card ${tone}`} key={title}><span className="stat-icon"><Icon/></span><strong>{value}</strong><span>{title}</span><ArrowRight className="stat-arrow"/></Link>)}</div><div className="dashboard-grid"><Panel title="Nächste Sitzungen" action={<Link to="/sitzungen">Alle Sitzungen</Link>}><div className="stack-list">{data.meetings.map(m=><Link className="stack-item" to={`/sitzungen/${m.id}`} key={String(m.id)}><div className="date-tile"><b>{new Date(String(m.starts_at)).toLocaleDateString("de-DE",{day:"2-digit"})}</b><span>{new Date(String(m.starts_at)).toLocaleDateString("de-DE",{month:"short"})}</span></div><div><strong>{m.title}</strong><span>{dateTime(m.starts_at)} · {m.location||"Ort offen"}</span></div><Status value={m.status}/></Link>)}{!data.meetings.length&&<div className="mini-empty"><CalendarDays/>Keine Sitzung geplant.</div>}</div></Panel><Panel title="Anstehende Fristen" action={<Link to="/aufgaben">Aufgaben öffnen</Link>}><div className="deadline-list">{data.deadlines.map(d=><Link className="deadline" to={d.entity_type==="case"?`/vorgaenge?open=${d.id}`:`/aufgaben?open=${d.id}`} key={String(d.id)}><AlertTriangle/><div><strong>{d.reference&&`${d.reference} · `}{d.title}</strong><span>Fällig {dateTime(d.due_at)}</span></div><Status value={d.priority}/></Link>)}{!data.deadlines.length&&<div className="mini-empty"><ClipboardCheck/>Aktuell keine Fristen.</div>}</div></Panel></div><Panel title="Letzte Aktivitäten" className="activity-panel"><div className="activity-strip">{data.activity.map(a=><div key={String(a.id)}><span className="activity-dot"/><strong>{String(a.action).replaceAll("_"," ")}</strong><span>{a.first_name||"System"} {a.last_name||""}</span><time>{dateTime(a.created_at)}</time></div>)}</div></Panel></>}
