import { useEffect, useState, type FormEvent } from "react";
import { Building2, KeyRound, Save, ShieldCheck, UserRoundCog, UsersRound } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "../AuthContext";
import { api, patch, post, type Row } from "../api";
import { RecordDrawer } from "../components/RecordDrawer";
import { Button, DataTable, EntityForm, ErrorBox, Modal, NewButton, PageHeader, Panel, Spinner, type FieldDef, useList } from "../components/UI";
import { label, Status } from "../components/Status";

function CommitteeMemberManager({committeeId,current,allMembers,onDone}:{committeeId:string;current:Row[];allMembers:Row[];onDone:()=>Promise<void>}){
  const [editing,setEditing]=useState(false),[busy,setBusy]=useState(false);
  const currentIds=new Set(current.map(member=>String(member.user_id)));
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget),members=allMembers.filter(member=>form.get(`member-${member.id}`)==="on").map(member=>({userId:member.id,function:form.get(`function-${member.id}`)||"Mitglied"}));await api(`/committees/${committeeId}/members`,{method:"PUT",body:JSON.stringify({members})});setBusy(false);setEditing(false);await onDone();};
  return <section className="detail-section"><header><h3>Ausschussbesetzung</h3><Button variant="ghost" onClick={()=>setEditing(value=>!value)} icon={<UserRoundCog/>}>{editing?"Abbrechen":"Besetzung ändern"}</Button></header>{editing?<form className="member-picker" onSubmit={submit}>{allMembers.filter(member=>member.active).map(member=><label key={String(member.id)}><input type="checkbox" name={`member-${member.id}`} defaultChecked={currentIds.has(String(member.id))}/><span className="avatar small">{String(member.first_name)[0]}{String(member.last_name)[0]}</span><strong>{member.first_name} {member.last_name}</strong><input name={`function-${member.id}`} defaultValue={String(current.find(item=>item.user_id===member.id)?.function||"Mitglied")} placeholder="Funktion"/></label>)}<Button type="submit" disabled={busy} icon={<Save/>}>{busy?"Speichert …":"Besetzung speichern"}</Button></form>:<div className="detail-relations">{current.map(member=><div className="relation-card" key={String(member.user_id)}><span><UsersRound/></span><div><strong>{member.first_name} {member.last_name}</strong><small>{member.function} · {label(member.role)}</small></div></div>)}{!current.length&&<div className="mini-empty">Noch keine Mitglieder zugeordnet.</div>}</div>}</section>;
}

export function MembersPage(){
  const {permissions}=useAuth(),members=useList("/members"),committees=useList("/committees"),[memberOpen,setMemberOpen]=useState(false),[committeeOpen,setCommitteeOpen]=useState(false),[committeeTick,setCommitteeTick]=useState(0),[params,setParams]=useSearchParams(),selectedMember=params.get("member"),selectedCommittee=params.get("committee"),canMembers=permissions?.includes("members:manage"),canCouncil=permissions?.includes("council:manage");
  const roleOptions=["admin","vorsitz","sekretariat","mitglied","ersatzmitglied","lesezugriff"].map(value=>({value,label:label(value)}));
  const memberFields:FieldDef[]=[{key:"firstName",label:"Vorname",required:true},{key:"lastName",label:"Nachname",required:true},{key:"email",label:"E-Mail",type:"email",required:true,span:2},{key:"role",label:"Rolle",type:"select",required:true,defaultValue:"mitglied",options:roleOptions},{key:"position",label:"Funktion"},{key:"phone",label:"Telefon"},{key:"substituteRank",label:"Ersatzrang",type:"number",min:1},{key:"temporaryPassword",label:"Temporäres Passwort",type:"password",required:true,span:2,placeholder:"Mindestens 12 Zeichen"}];
  const memberEditFields:FieldDef[]=memberFields.map(field=>field.key==="temporaryPassword"?{...field,required:false,label:"Neues Initialpasswort (optional)"}:field).concat({key:"active",label:"Zugang aktiv",type:"checkbox",defaultValue:true});
  const committeeFields:FieldDef[]=[{key:"name",label:"Name",required:true},{key:"kind",label:"Art",type:"select",defaultValue:"ausschuss",options:["gremium","ausschuss","arbeitsgruppe","jav","sbv","wahlvorstand"].map(value=>({value,label:label(value)}))},{key:"description",label:"Auftrag / Beschreibung",type:"textarea",span:2}];
  const setSelection=(key:"member"|"committee",id:string|null)=>{const next=new URLSearchParams(params);next.delete("member");next.delete("committee");if(id)next.set(key,id);setParams(next,{replace:!id});};
  return <><PageHeader eyebrow="Gremiumsstruktur" title="Mitglieder & Ausschüsse" description="Rollen, Vertretungen und Zuständigkeiten transparent organisieren." action={(canMembers||canCouncil)?<div className="action-row">{canCouncil&&<NewButton label="Ausschuss anlegen" onClick={()=>setCommitteeOpen(true)}/>} {canMembers&&<NewButton label="Mitglied einladen" onClick={()=>setMemberOpen(true)}/>}</div>:undefined}/><div className="organization-grid"><Panel title="Mitglieder"><DataTable items={members.items} onRowClick={row=>setSelection("member",String(row.id))} columns={[{key:"name",label:"Mitglied",render:row=><div className="member-cell"><span className="avatar">{String(row.first_name)[0]}{String(row.last_name)[0]}</span><div><strong>{row.first_name} {row.last_name}</strong><span>{row.email}</span></div></div>},{key:"role",label:"Rolle",render:row=><Status value={row.role}/>},{key:"position",label:"Funktion"},{key:"last_login_at",label:"Zugang",render:row=><Status value={row.active?"aktiv":"deaktiviert"}/>}]}/></Panel><Panel title="Gremien & Ausschüsse"><div className="committee-grid">{committees.items.map(committee=><button className="committee-card" onClick={()=>setSelection("committee",String(committee.id))} key={String(committee.id)}><span><UsersRound/></span><div><strong>{committee.name}</strong><p>{committee.description||label(committee.kind)}</p><small>{committee.member_count} Mitglieder</small></div><i>Öffnen</i></button>)}</div></Panel></div><Modal title="Mitglied einladen" open={memberOpen} onClose={()=>setMemberOpen(false)} wide><EntityForm fields={memberFields} onSubmit={async values=>{const result=await post<{id:string}>("/members",values);setMemberOpen(false);await members.reload();setSelection("member",result.id);}} submitLabel="Zugang anlegen"/></Modal><Modal title="Ausschuss oder Arbeitsgruppe" open={committeeOpen} onClose={()=>setCommitteeOpen(false)}><EntityForm fields={committeeFields} onSubmit={async values=>{const result=await post<{id:string}>("/committees",values);setCommitteeOpen(false);await committees.reload();setSelection("committee",result.id);}}/></Modal><RecordDrawer endpoint="/members" selectedId={selectedMember} onClose={()=>setSelection("member",null)} fields={memberEditFields} eyebrow="Gremiumsmitglied" titleKey="display_name" referenceKey="email" editPermission="members:manage" onUpdated={members.reload}/><RecordDrawer key={`${selectedCommittee}-${committeeTick}`} endpoint="/committees" selectedId={selectedCommittee} onClose={()=>setSelection("committee",null)} fields={committeeFields} eyebrow="Gremium" titleKey="name" editPermission="council:manage" onUpdated={committees.reload} renderFeature={(item,related)=>canCouncil?<CommitteeMemberManager committeeId={String(item.id)} current={related.members||[]} allMembers={members.items} onDone={async()=>{await committees.reload();setCommitteeTick(value=>value+1);}}/>:undefined}/></>;
}

export function SettingsPage(){
  const [council,setCouncil]=useState<Row|null>(null),[error,setError]=useState(""),[saved,setSaved]=useState(false);
  useEffect(()=>{api<{council:Row}>("/council").then(data=>setCouncil(data.council)).catch(reason=>setError(reason instanceof Error?reason.message:"Fehler"));},[]);
  if(error)return <ErrorBox message={error}/>;if(!council)return <Spinner/>;
  return <><PageHeader eyebrow="Administration" title="Gremium konfigurieren" description="Stammdaten und organisatorische Leitplanken für die Plattform."/><div className="settings-grid"><Panel><div className="settings-intro"><span><Building2/></span><div><h2>{council.name}</h2><p>{council.company_name||"Unternehmen noch nicht hinterlegt"}</p></div></div><EntityForm initial={{name:council.name,companyName:council.company_name,address:council.address,termStart:council.term_start,termEnd:council.term_end,meetingNoticeDays:council.meeting_notice_days}} fields={[{key:"name",label:"Gremiumsname",required:true},{key:"companyName",label:"Unternehmen"},{key:"address",label:"Anschrift",type:"textarea",span:2},{key:"termStart",label:"Amtszeit von",type:"date"},{key:"termEnd",label:"Amtszeit bis",type:"date"},{key:"meetingNoticeDays",label:"Standard-Ladungsfrist (Tage)",type:"number",min:0}]} onSubmit={async values=>{await patch("/council",values);setSaved(true);setTimeout(()=>setSaved(false),2500);}} submitLabel={saved?"Gespeichert":"Änderungen speichern"}/></Panel><aside className="settings-aside"><div><ShieldCheck/><strong>Sicherheitsgrundsätze</strong><p>Least-Privilege-Rollen, serverseitige Sitzungen, CSRF-Schutz und protokollierte Änderungen sind aktiv.</p></div><div><KeyRound/><strong>Datenschutz</strong><p>Keine Tracker, keine externen Schriftarten, lokale Datenhaltung und verschlüsselte Dateiinhalte.</p></div></aside></div></>;
}
