import { useMemo, useState } from "react";
import { Download, Info, Plus } from "lucide-react";
import { api, dateOnly, dateTime, euro, post, type Row } from "../api";
import { DataTable, EntityForm, ErrorBox, Modal, NewButton, PageHeader, Panel, Spinner, type Column, type FieldDef, useList } from "../components/UI";
import { label, Status } from "../components/Status";

const statuses=(values:string[])=>values.map(value=>({value,label:label(value)}));
const priority=statuses(["niedrig","normal","hoch","kritisch"]);
function MemberFields({includeCases=false}:{includeCases?:boolean}={}){const members=useList("/members"),cases=useList("/cases");return {memberOptions:members.items.filter(m=>m.active).map(m=>({value:String(m.id),label:`${m.first_name} ${m.last_name}`})),caseOptions:includeCases?cases.items.map(c=>({value:String(c.id),label:`${c.reference} · ${c.title}`})):[]};}

function EntityPage({title,eyebrow,description,endpoint,fields,columns,createLabel="Neu anlegen",notice}:{title:string;eyebrow:string;description:string;endpoint:string;fields:FieldDef[];columns:Column[];createLabel?:string;notice?:string}){const {items,loading,error,reload}=useList(endpoint),[open,setOpen]=useState(false);const create=async(data:Record<string,unknown>)=>{await post(endpoint,data);setOpen(false);await reload();};return <><PageHeader eyebrow={eyebrow} title={title} description={description} action={<NewButton label={createLabel} onClick={()=>setOpen(true)}/>} />{notice&&<div className="notice"><Info/>{notice}</div>}<Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} columns={columns}/>}</Panel><Modal title={createLabel} open={open} onClose={()=>setOpen(false)} wide><EntityForm fields={fields} onSubmit={create}/></Modal></>}

export function CasesPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Mitbestimmung" title="Vorgänge & Fristen" description="Beteiligungsverfahren vom Eingang bis zum Beschluss lückenlos steuern." endpoint="/cases" createLabel="Vorgang anlegen" fields={[
  {key:"title",label:"Titel",required:true,span:2},{key:"category",label:"Kategorie",type:"select",required:true,options:statuses(["personelle_massnahme","technische_einrichtung","arbeitszeit","gesundheitsschutz","umstrukturierung","wirtschaftsausschuss","sonstiges"])},{key:"legalBasis",label:"Rechtsgrundlage",placeholder:"z. B. § 87 Abs. 1 Nr. 6 BetrVG"},{key:"description",label:"Sachverhalt",type:"textarea",span:2},{key:"priority",label:"Priorität",type:"select",defaultValue:"normal",options:priority},{key:"status",label:"Status",type:"select",defaultValue:"neu",options:statuses(["neu","in_pruefung","verhandlung","beschlossen","erledigt"])},{key:"receivedAt",label:"Eingang",type:"datetime-local"},{key:"dueAt",label:"Frist",type:"datetime-local"},{key:"responsibleId",label:"Verantwortlich",type:"select",options:memberOptions}
]} columns={[
  {key:"reference",label:"Aktenzeichen",className:"mono"},{key:"title",label:"Vorgang",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{label(r.category)}</span></div>},{key:"responsible",label:"Verantwortlich",render:r=>r.responsible_first_name?`${r.responsible_first_name} ${r.responsible_last_name}`:"—"},{key:"due_at",label:"Frist",render:r=>dateTime(r.due_at)},{key:"priority",label:"Priorität",render:r=><Status value={r.priority}/>},{key:"status",label:"Status",render:r=><Status value={r.status}/>}
]}/>}

export function TasksPage(){const {memberOptions,caseOptions}=MemberFields({includeCases:true});return <EntityPage eyebrow="Zusammenarbeit" title="Aufgaben" description="Verantwortlichkeiten, Status und Termine gemeinsam im Blick behalten." endpoint="/tasks" createLabel="Aufgabe anlegen" fields={[
  {key:"title",label:"Aufgabe",required:true,span:2},{key:"description",label:"Beschreibung",type:"textarea",span:2},{key:"assignedTo",label:"Zuständig",type:"select",options:memberOptions},{key:"dueAt",label:"Fällig am",type:"datetime-local"},{key:"priority",label:"Priorität",type:"select",defaultValue:"normal",options:priority},{key:"status",label:"Status",type:"select",defaultValue:"offen",options:statuses(["offen","in_arbeit","wartet","erledigt"])},{key:"caseId",label:"Verknüpfter Vorgang",type:"select",options:caseOptions,span:2}
]} columns={[{key:"title",label:"Aufgabe",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.case_reference||r.description||"Ohne Vorgang"}</span></div>},{key:"assigned",label:"Zuständig",render:r=>r.assigned_first_name?`${r.assigned_first_name} ${r.assigned_last_name}`:"Offen"},{key:"due_at",label:"Fällig",render:r=>dateTime(r.due_at)},{key:"priority",label:"Priorität",render:r=><Status value={r.priority}/>},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function InquiriesPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Vertrauensarbeit" title="Mitarbeiteranfragen" description="Vertrauliche Anliegen geschützt aufnehmen und nachvollziehbar bearbeiten." endpoint="/inquiries" createLabel="Anfrage aufnehmen" notice="Personenbezogene Angaben nur im erforderlichen Umfang erfassen. Eine Weitergabe an Dritte setzt regelmäßig die Einwilligung der betroffenen Person voraus." fields={[
  {key:"subject",label:"Betreff",required:true,span:2},{key:"requesterName",label:"Name / Pseudonym",required:true},{key:"requesterContact",label:"Kontakt (optional)"},{key:"channel",label:"Eingangskanal",type:"select",defaultValue:"persoenlich",options:statuses(["persoenlich","telefon","email","brief","sprechstunde"])},{key:"category",label:"Kategorie",type:"select",defaultValue:"beratung",options:statuses(["beratung","arbeitszeit","konflikt","kuendigung","gesundheit","gleichstellung","beschwerde"])},{key:"description",label:"Anliegen",type:"textarea",required:true,span:2},{key:"consentRecorded",label:"Einwilligung zur Bearbeitung dokumentiert",type:"checkbox",span:2},{key:"assignedTo",label:"Verantwortlich",type:"select",options:memberOptions},{key:"dueAt",label:"Wiedervorlage",type:"datetime-local"}
]} columns={[{key:"reference",label:"Referenz",className:"mono"},{key:"subject",label:"Anliegen",render:r=><div className="primary-cell"><strong>{r.subject}</strong><span>{r.requester_name} · {label(r.category)}</span></div>},{key:"assigned",label:"Verantwortlich",render:r=>r.assigned_first_name?`${r.assigned_first_name} ${r.assigned_last_name}`:"—"},{key:"due_at",label:"Wiedervorlage",render:r=>dateTime(r.due_at)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function AgreementsPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Regelungswerk" title="Betriebsvereinbarungen" description="Entwürfe, Verhandlungen, Laufzeiten und Nachwirkung zentral verwalten." endpoint="/agreements" createLabel="Vereinbarung anlegen" fields={[
  {key:"title",label:"Titel",required:true,span:2},{key:"category",label:"Themenfeld",type:"select",options:statuses(["arbeitszeit","mobile_arbeit","datenschutz","it_ki","gesundheit","entgelt","qualifizierung","sonstiges"])},{key:"status",label:"Status",type:"select",defaultValue:"entwurf",options:statuses(["entwurf","verhandlung","gueltig","gekuendigt","ausgelaufen"])},{key:"summary",label:"Kurzbeschreibung",type:"textarea",span:2},{key:"validFrom",label:"Gültig ab",type:"date"},{key:"validUntil",label:"Gültig bis",type:"date"},{key:"noticePeriod",label:"Kündigungsfrist"},{key:"reviewAt",label:"Überprüfung am",type:"date"},{key:"ownerId",label:"Federführung",type:"select",options:memberOptions},{key:"afterEffect",label:"Nachwirkung vereinbart",type:"checkbox"}
]} columns={[{key:"reference",label:"Referenz",className:"mono"},{key:"title",label:"Vereinbarung",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{label(r.category)}</span></div>},{key:"valid_from",label:"Laufzeit",render:r=><>{dateOnly(r.valid_from)}{r.valid_until&&` – ${dateOnly(r.valid_until)}`}</>},{key:"review_at",label:"Wiedervorlage",render:r=>dateOnly(r.review_at)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function DecisionsPage(){const {items,loading,error}=useList("/decisions");return <><PageHeader eyebrow="Beschlussarchiv" title="Beschlüsse" description="Volltext, Abstimmungsergebnisse und Verknüpfungen dauerhaft auffindbar." action={<a className="button secondary" href="/api/calendar.ics"><Download/>Kalender exportieren</a>}/><Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} columns={[{key:"reference",label:"Beschluss",className:"mono"},{key:"title",label:"Gegenstand",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.resolution_text}</span></div>},{key:"decided_at",label:"Beschlossen",render:r=>dateOnly(r.decided_at)},{key:"votes",label:"Abstimmung",render:r=><span className="votes"><b>{r.vote_yes} Ja</b> · {r.vote_no} Nein · {r.vote_abstain} Enth.</span>},{key:"result",label:"Ergebnis",render:r=><Status value={r.result}/>} ]}/>}</Panel></>}

export function TrainingsPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Qualifizierung" title="Seminare & Schulungen" description="Bildungsbedarf, Entsendebeschlüsse, Buchung und Kostenplanung bündeln." endpoint="/trainings" createLabel="Schulung planen" fields={[
  {key:"userId",label:"Teilnehmendes Mitglied",type:"select",required:true,options:memberOptions},{key:"title",label:"Seminar",required:true},{key:"provider",label:"Anbieter"},{key:"status",label:"Status",type:"select",defaultValue:"bedarf",options:statuses(["bedarf","beantragt","beschlossen","gebucht","abgeschlossen","abgelehnt"])},{key:"startsAt",label:"Beginn",type:"datetime-local",required:true},{key:"endsAt",label:"Ende",type:"datetime-local",required:true},{key:"costEuro",label:"Kosten (EUR)",type:"number",step:0.01,min:0},{key:"notes",label:"Notizen / Erforderlichkeit",type:"textarea",span:2}
]} columns={[{key:"title",label:"Schulung",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.provider}</span></div>},{key:"member",label:"Mitglied",render:r=>`${r.first_name} ${r.last_name}`},{key:"starts_at",label:"Zeitraum",render:r=><>{dateOnly(r.starts_at)} – {dateOnly(r.ends_at)}</>},{key:"cost_cents",label:"Kosten",render:r=>euro(r.cost_cents)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function AuditPage(){const {items,loading,error}=useList("/audit");const columns:Column[]=useMemo(()=>[{key:"created_at",label:"Zeit",render:r=>dateTime(r.created_at)},{key:"user",label:"Benutzer",render:r=>r.first_name?`${r.first_name} ${r.last_name}`:"System"},{key:"action",label:"Aktion",render:r=><Status value={r.action}/>},{key:"entity_type",label:"Objekt",render:r=><span>{label(r.entity_type)} <code>{String(r.entity_id||"").slice(0,8)}</code></span>},{key:"ip_address",label:"IP-Adresse"}],[]);return <><PageHeader eyebrow="Nachvollziehbarkeit" title="Audit-Protokoll" description="Unveränderliche Übersicht sicherheits- und fachlich relevanter Aktionen."/><Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} columns={columns}/>}</Panel></>}
