import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, Check, Circle, Download, Info, Search, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { api, dateOnly, dateTime, euro, post, type Row } from "../api";
import { Button, DataTable, Drawer, EntityForm, ErrorBox, Modal, NewButton, PageHeader, Panel, Spinner, type Column, type FieldDef, useList } from "../components/UI";
import { label, Status } from "../components/Status";
import { RecordDrawer } from "../components/RecordDrawer";
import { useAuth } from "../AuthContext";

const statuses=(values:string[])=>values.map(value=>({value,label:label(value)}));
const priority=statuses(["niedrig","normal","hoch","kritisch"]);
function MemberFields({includeCases=false}:{includeCases?:boolean}={}){const members=useList("/members"),cases=useList("/cases");return {memberOptions:members.items.filter(m=>m.active).map(m=>({value:String(m.id),label:`${m.first_name} ${m.last_name}`})),caseOptions:includeCases?cases.items.map(c=>({value:String(c.id),label:`${c.reference} · ${c.title}`})):[]};}

const permissionByEndpoint:Record<string,string>={"/cases":"cases:write","/tasks":"tasks:write","/inquiries":"inquiries:write","/agreements":"agreements:write","/trainings":"trainings:write"};
function EntityPage({title,eyebrow,description,endpoint,fields,columns,createLabel="Neu anlegen",notice,extraAction,renderFeature}:{title:string;eyebrow:string;description:string;endpoint:string;fields:FieldDef[];columns:Column[];createLabel?:string;notice?:string;extraAction?:(actions:{reload:()=>Promise<void>;openRecord:(id:string)=>void})=>ReactNode;renderFeature?:(item:Row,related:Record<string,Row[]>)=>ReactNode}){
  const {permissions}=useAuth(),{items,loading,error,reload}=useList(endpoint),[open,setOpen]=useState(false),[params,setParams]=useSearchParams(),selectedId=params.get("open"),permission=permissionByEndpoint[endpoint],canWrite=Boolean(permission&&permissions?.includes(permission)),titleKey=endpoint==="/inquiries"?"subject":"title";
  const openRecord=(id:string)=>{const next=new URLSearchParams(params);next.set("open",id);next.delete("assistant");next.delete("topic");setParams(next);};
  const select=(row:Row)=>openRecord(String(row.id));
  const close=()=>{const next=new URLSearchParams(params);next.delete("open");setParams(next,{replace:true});};
  const create=async(data:Record<string,unknown>)=>{const result=await post<{id?:string}>(endpoint,data);setOpen(false);await reload();if(result.id)openRecord(result.id);};
  const secondary=canWrite&&extraAction?.({reload,openRecord});
  return <><PageHeader eyebrow={eyebrow} title={title} description={description} action={canWrite?<div className="action-row">{secondary}<NewButton label={createLabel} onClick={()=>setOpen(true)}/></div>:undefined}/>{notice&&<div className="notice"><Info/>{notice}</div>}<Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} columns={columns} onRowClick={select}/>}</Panel><Modal title={createLabel} open={open} onClose={()=>setOpen(false)} wide><EntityForm fields={fields} onSubmit={create}/></Modal><RecordDrawer endpoint={endpoint} selectedId={selectedId} onClose={close} fields={fields} eyebrow={eyebrow} titleKey={titleKey} editPermission={permission} onUpdated={reload} renderFeature={renderFeature}/></>;
}

interface ProcedureStep{key:string;title:string;description:string;offsetDays?:number;priority:string}
interface ProcedureTemplate{id:string;title:string;group:string;category:string;situation:string;plainLanguage:string;firstQuestion:string;legalSections:string[];riskLevel:string;deadlineDays?:number;deadlineNote:string;steps:ProcedureStep[]}

function ProcedureAssistant({onCreated}:{onCreated:(id:string)=>Promise<void>}){
  const [params,setParams]=useSearchParams(),requested=params.get("assistant"),[open,setOpen]=useState(Boolean(requested)),[templates,setTemplates]=useState<ProcedureTemplate[]>([]),[selected,setSelected]=useState<ProcedureTemplate|null>(null),[query,setQuery]=useState(params.get("topic")||""),members=useList("/members"),meetings=useList("/meetings"),[error,setError]=useState("");
  useEffect(()=>{api<{items:ProcedureTemplate[]}>("/procedure-templates").then(data=>{setTemplates(data.items);if(requested&&requested!=="1")setSelected(data.items.find(item=>item.id===requested)||null);}).catch(reason=>setError(reason instanceof Error?reason.message:"Standardverfahren konnten nicht geladen werden."));},[requested]);
  useEffect(()=>{if(requested)setOpen(true);},[requested]);
  const close=()=>{setOpen(false);setSelected(null);const next=new URLSearchParams(params);next.delete("assistant");next.delete("topic");setParams(next,{replace:true});};
  const needle=query.toLocaleLowerCase("de-DE"),filtered=templates.filter(item=>`${item.title} ${item.group} ${item.situation} ${item.plainLanguage}`.toLocaleLowerCase("de-DE").includes(needle));
  const fields:FieldDef[]=selected?[{key:"title",label:"Eigener Titel",required:true,span:2,defaultValue:selected.title},{key:"receivedAt",label:"Eingang / Bekanntwerden",type:"datetime-local",defaultValue:new Date().toISOString().slice(0,16)},{key:"responsibleId",label:"Verantwortliches Mitglied",type:"select",options:members.items.filter(item=>item.active).map(item=>({value:String(item.id),label:`${item.first_name} ${item.last_name}`}))},{key:"meetingId",label:"Direkt auf eine Sitzung setzen (optional)",type:"select",span:2,options:meetings.items.map(item=>({value:String(item.id),label:`Sitzung ${item.sequence_no} · ${dateTime(item.starts_at)} · ${item.title}`}))}]:[];
  return <><Button variant="secondary" icon={<Sparkles/>} onClick={()=>setOpen(true)}>Standardverfahren starten</Button><Modal title="Geführtes Standardverfahren" open={open} onClose={close} wide>{error&&<ErrorBox message={error}/>} {!templates.length&&!error?<Spinner/>:selected?<div className="procedure-selected"><button className="procedure-back" onClick={()=>setSelected(null)}><ArrowLeft/>Anderen Fall wählen</button><div className="procedure-summary"><span><Workflow/></span><div><small>{selected.group} · Risiko {label(selected.riskLevel)}</small><h3>{selected.title}</h3><p>{selected.plainLanguage}</p></div></div><div className="procedure-first-question"><Sparkles/><div><strong>Zuerst klären</strong><p>{selected.firstQuestion}</p></div></div><div className="procedure-legal-row">{selected.legalSections.map(section=><Link target="_blank" to={`/rechtswissen?open=${section}`} key={section}>§ {section} BetrVG</Link>)}</div><section className="procedure-preview"><header><strong>Diese Checkliste wird automatisch angelegt</strong><span>{selected.steps.length} Aufgaben</span></header>{selected.steps.map((item,index)=><div key={item.key}><b>{index+1}</b><span><strong>{item.title}</strong><small>{item.description}</small></span>{item.offsetDays!==undefined&&<em>Tag {item.offsetDays}</em>}</div>)}</section>{selected.deadlineDays!==undefined&&<div className="procedure-deadline"><Info/><span><strong>Fristorientierung: {selected.deadlineDays} Kalendertage</strong>{selected.deadlineNote}</span></div>}<EntityForm fields={fields} submitLabel={`${selected.steps.length} Aufgaben und Vorgang anlegen`} onSubmit={async values=>{const result=await post<{id:string}>(`/procedure-templates/${selected.id}/start`,values);close();await onCreated(result.id);}}/></div>:<div className="procedure-catalog"><div className="procedure-intro"><Sparkles/><div><strong>Was ist passiert?</strong><p>Wählen Sie die Alltagssituation. Die Software legt Rechtsgrundlagen, Prüfpfad, Aufgaben und eine vorsichtige Fristorientierung für Sie an.</p></div></div><div className="search-input"><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="z. B. Kündigung, neue Software, Schichtplan …"/></div><div className="procedure-grid">{filtered.map(item=><button onClick={()=>setSelected(item)} key={item.id}><span className={`risk-dot ${item.riskLevel}`}/><small>{item.group}</small><strong>{item.title}</strong><p>{item.situation}</p><footer><span>{item.steps.length} Schritte</span><span>{item.legalSections.length} Rechtsgrundlagen</span></footer></button>)}</div>{!filtered.length&&<div className="legal-no-results"><Search/><strong>Kein Standardfall gefunden</strong><p>Versuchen Sie einen allgemeineren Begriff oder legen Sie den Vorgang manuell an.</p></div>}</div>}</Modal></>;
}

function CaseProcedureFeature({item,related}:{item:Row;related:Record<string,Row[]>}){
  const templateId=String(item.procedure_template_id||"");
  const [template,setTemplate]=useState<ProcedureTemplate|null>(null);
  useEffect(()=>{if(templateId)api<{item:ProcedureTemplate}>(`/procedure-templates/${templateId}`).then(data=>setTemplate(data.item)).catch(()=>setTemplate(null));},[templateId]);
  if(!templateId||!template)return null;
  const tasks=related.tasks||[],done=tasks.filter(task=>task.status==="erledigt").length,byStep=new Map(tasks.map(task=>[String(task.workflow_step),task]));
  return <section className="case-workflow"><header><div><span><Sparkles/></span><div><small>Geführtes Standardverfahren</small><strong>{template.title}</strong></div></div><b>{done}/{template.steps.length}</b></header><div className="workflow-progress"><i style={{width:`${template.steps.length?done/template.steps.length*100:0}%`}}/></div><p>{template.plainLanguage}</p><div className="workflow-steps">{template.steps.map((workflow,index)=>{const task=byStep.get(workflow.key),complete=task?.status==="erledigt";return task?<Link to={`/aufgaben?open=${task.id}`} key={workflow.key} className={complete?"complete":""}>{complete?<Check/>:<Circle/>}<span><strong>{index+1}. {workflow.title}</strong><small>{complete?"Erledigt":task.status==="in_arbeit"?"In Arbeit":"Offen"}{task.due_at&&` · ${dateTime(task.due_at)}`}</small></span></Link>:null;})}</div><div className="legal-disclaimer">{template.deadlineNote}</div></section>;
}

export function CasesPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Mitbestimmung" title="Vorgänge & Fristen" description="Wählen Sie einen Standardfall oder erfassen Sie frei – Rechtsgrundlagen, Prüfschritte und Zusammenhänge bleiben an einem Ort." endpoint="/cases" createLabel="Vorgang frei anlegen" extraAction={({reload,openRecord})=><ProcedureAssistant onCreated={async id=>{await reload();openRecord(id);}}/>} renderFeature={(item,related)=><CaseProcedureFeature item={item} related={related}/>} fields={[
  {key:"title",label:"Titel",required:true,span:2},{key:"category",label:"Kategorie",type:"select",required:true,options:statuses(["kuendigung","personelle_massnahme","technische_einrichtung","arbeitszeit","gesundheitsschutz","beschwerde","gleichstellung","betriebsvereinbarung","umstrukturierung","wirtschaftsausschuss","personalplanung","schulung","wahl","datenschutz","gremienarbeit","sonstiges"])},{key:"legalBasis",label:"Rechtsgrundlage (optional)",placeholder:"Kann später per Themenvorschlag zugeordnet werden"},{key:"description",label:"Was ist passiert?",type:"textarea",span:2,placeholder:"Beschreiben Sie den Sachverhalt in eigenen Worten. Juristische Begriffe sind nicht nötig."},{key:"priority",label:"Priorität",type:"select",defaultValue:"normal",options:priority},{key:"status",label:"Status",type:"select",defaultValue:"neu",options:statuses(["neu","in_pruefung","verhandlung","beschlossen","erledigt"])},{key:"receivedAt",label:"Eingang",type:"datetime-local"},{key:"dueAt",label:"Frist / Wiedervorlage",type:"datetime-local"},{key:"responsibleId",label:"Verantwortlich",type:"select",options:memberOptions}
]} columns={[
  {key:"reference",label:"Aktenzeichen",className:"mono"},{key:"title",label:"Vorgang",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{label(r.category)}</span></div>},{key:"responsible",label:"Verantwortlich",render:r=>r.responsible_first_name?`${r.responsible_first_name} ${r.responsible_last_name}`:"—"},{key:"due_at",label:"Frist",render:r=>dateTime(r.due_at)},{key:"priority",label:"Priorität",render:r=><Status value={r.priority}/>},{key:"status",label:"Status",render:r=><Status value={r.status}/>}
]}/>}

export function TasksPage(){const {memberOptions,caseOptions}=MemberFields({includeCases:true}),meetings=useList("/meetings");return <EntityPage eyebrow="Zusammenarbeit" title="Aufgaben" description="Verantwortlichkeiten, Status und Termine gemeinsam im Blick behalten." endpoint="/tasks" createLabel="Aufgabe anlegen" fields={[
  {key:"title",label:"Aufgabe",required:true,span:2},{key:"description",label:"Beschreibung",type:"textarea",span:2},{key:"assignedTo",label:"Zuständig",type:"select",options:memberOptions},{key:"dueAt",label:"Fällig am",type:"datetime-local"},{key:"priority",label:"Priorität",type:"select",defaultValue:"normal",options:priority},{key:"status",label:"Status",type:"select",defaultValue:"offen",options:statuses(["offen","in_arbeit","wartet","erledigt"])},{key:"caseId",label:"Verknüpfter Vorgang",type:"select",options:caseOptions},{key:"meetingId",label:"Verknüpfte Sitzung",type:"select",options:meetings.items.map(item=>({value:String(item.id),label:`Sitzung ${item.sequence_no} · ${item.title}`}))}
]} columns={[{key:"title",label:"Aufgabe",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.case_reference||r.description||"Ohne Vorgang"}</span></div>},{key:"assigned",label:"Zuständig",render:r=>r.assigned_first_name?`${r.assigned_first_name} ${r.assigned_last_name}`:"Offen"},{key:"due_at",label:"Fällig",render:r=>dateTime(r.due_at)},{key:"priority",label:"Priorität",render:r=><Status value={r.priority}/>},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function InquiriesPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Vertrauensarbeit" title="Mitarbeiteranfragen" description="Vertrauliche Anliegen geschützt aufnehmen und nachvollziehbar bearbeiten." endpoint="/inquiries" createLabel="Anfrage aufnehmen" notice="Personenbezogene Angaben nur im erforderlichen Umfang erfassen. Eine Weitergabe an Dritte setzt regelmäßig die Einwilligung der betroffenen Person voraus." fields={[
  {key:"subject",label:"Betreff",required:true,span:2},{key:"requesterName",label:"Name / Pseudonym",required:true},{key:"requesterContact",label:"Kontakt (optional)"},{key:"channel",label:"Eingangskanal",type:"select",defaultValue:"persoenlich",options:statuses(["persoenlich","telefon","email","brief","sprechstunde"])},{key:"category",label:"Kategorie",type:"select",defaultValue:"beratung",options:statuses(["beratung","arbeitszeit","konflikt","kuendigung","gesundheit","gleichstellung","beschwerde"])},{key:"description",label:"Anliegen",type:"textarea",required:true,span:2},{key:"consentRecorded",label:"Einwilligung zur Bearbeitung dokumentiert",type:"checkbox",span:2},{key:"assignedTo",label:"Verantwortlich",type:"select",options:memberOptions},{key:"dueAt",label:"Wiedervorlage",type:"datetime-local"},{key:"status",label:"Bearbeitungsstatus",type:"select",defaultValue:"neu",options:statuses(["neu","in_bearbeitung","wartet","erledigt","archiviert"])},{key:"outcome",label:"Ergebnis / nächste Schritte",type:"textarea",span:2}
]} columns={[{key:"reference",label:"Referenz",className:"mono"},{key:"subject",label:"Anliegen",render:r=><div className="primary-cell"><strong>{r.subject}</strong><span>{r.requester_name} · {label(r.category)}</span></div>},{key:"assigned",label:"Verantwortlich",render:r=>r.assigned_first_name?`${r.assigned_first_name} ${r.assigned_last_name}`:"—"},{key:"due_at",label:"Wiedervorlage",render:r=>dateTime(r.due_at)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function AgreementsPage(){const {memberOptions}=MemberFields();return <EntityPage eyebrow="Regelungswerk" title="Betriebsvereinbarungen" description="Entwürfe, Verhandlungen, Laufzeiten und Nachwirkung zentral verwalten." endpoint="/agreements" createLabel="Vereinbarung anlegen" fields={[
  {key:"title",label:"Titel",required:true,span:2},{key:"category",label:"Themenfeld",type:"select",options:statuses(["arbeitszeit","mobile_arbeit","datenschutz","it_ki","gesundheit","entgelt","qualifizierung","sonstiges"])},{key:"status",label:"Status",type:"select",defaultValue:"entwurf",options:statuses(["entwurf","verhandlung","gueltig","gekuendigt","ausgelaufen"])},{key:"summary",label:"Kurzbeschreibung",type:"textarea",span:2},{key:"validFrom",label:"Gültig ab",type:"date"},{key:"validUntil",label:"Gültig bis",type:"date"},{key:"noticePeriod",label:"Kündigungsfrist"},{key:"reviewAt",label:"Überprüfung am",type:"date"},{key:"ownerId",label:"Federführung",type:"select",options:memberOptions},{key:"afterEffect",label:"Nachwirkung vereinbart",type:"checkbox"}
]} columns={[{key:"reference",label:"Referenz",className:"mono"},{key:"title",label:"Vereinbarung",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{label(r.category)}</span></div>},{key:"valid_from",label:"Laufzeit",render:r=><>{dateOnly(r.valid_from)}{r.valid_until&&` – ${dateOnly(r.valid_until)}`}</>},{key:"review_at",label:"Wiedervorlage",render:r=>dateOnly(r.review_at)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function DecisionsPage(){const {items,loading,error}=useList("/decisions"),[params,setParams]=useSearchParams(),selectedId=params.get("open"),close=()=>{const next=new URLSearchParams(params);next.delete("open");setParams(next,{replace:true});};const fields:FieldDef[]=[{key:"resolutionText",label:"Beschlusstext",type:"textarea",span:2},{key:"decidedAt",label:"Beschlossen am",type:"datetime-local"},{key:"votingMethod",label:"Abstimmungsart",type:"select",options:["offen","geheim","namentlich","umlauf"].map(value=>({value,label:label(value)}))},{key:"eligibleVoters",label:"Stimmberechtigte",type:"number"},{key:"voteYes",label:"Ja-Stimmen",type:"number"},{key:"voteNo",label:"Nein-Stimmen",type:"number"},{key:"voteAbstain",label:"Enthaltungen",type:"number"},{key:"meetingTitle",label:"Sitzung"},{key:"caseReference",label:"Vorgang"}];return <><PageHeader eyebrow="Beschlussarchiv" title="Beschlüsse" description="Volltext, Abstimmungsergebnisse und Verknüpfungen dauerhaft auffindbar." action={<a className="button secondary" href="/api/calendar.ics"><Download/>Kalender exportieren</a>}/><Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} onRowClick={row=>{const next=new URLSearchParams(params);next.set("open",String(row.id));setParams(next);}} columns={[{key:"reference",label:"Beschluss",className:"mono"},{key:"title",label:"Gegenstand",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.resolution_text}</span></div>},{key:"decided_at",label:"Beschlossen",render:r=>dateOnly(r.decided_at)},{key:"votes",label:"Abstimmung",render:r=><span className="votes"><b>{r.vote_yes} Ja</b> · {r.vote_no} Nein · {r.vote_abstain} Enth.</span>},{key:"result",label:"Ergebnis",render:r=><Status value={r.result}/>} ]}/>}</Panel><RecordDrawer endpoint="/decisions" selectedId={selectedId} onClose={close} fields={fields} eyebrow="Beschluss" readOnly renderFeature={item=><div className="vote-result"><div><strong>{item.vote_yes}</strong><span>Ja</span></div><div><strong>{item.vote_no}</strong><span>Nein</span></div><div><strong>{item.vote_abstain}</strong><span>Enthaltung</span></div><Status value={item.result}/></div>}/></>}

export function TrainingsPage(){const {memberOptions}=MemberFields(),decisions=useList("/decisions");return <EntityPage eyebrow="Qualifizierung" title="Seminare & Schulungen" description="Bildungsbedarf, Entsendebeschlüsse, Buchung und Kostenplanung bündeln." endpoint="/trainings" createLabel="Schulung planen" fields={[
  {key:"userId",label:"Teilnehmendes Mitglied",type:"select",required:true,options:memberOptions},{key:"title",label:"Seminar",required:true},{key:"provider",label:"Anbieter"},{key:"status",label:"Status",type:"select",defaultValue:"bedarf",options:statuses(["bedarf","beantragt","beschlossen","gebucht","abgeschlossen","abgelehnt"])},{key:"startsAt",label:"Beginn",type:"datetime-local",required:true},{key:"endsAt",label:"Ende",type:"datetime-local",required:true},{key:"costEuro",label:"Kosten (EUR)",type:"number",step:0.01,min:0},{key:"decisionId",label:"Entsendebeschluss",type:"select",options:decisions.items.map(item=>({value:String(item.id),label:`${item.reference} · ${item.title}`}))},{key:"notes",label:"Notizen / Erforderlichkeit",type:"textarea",span:2}
]} columns={[{key:"title",label:"Schulung",render:r=><div className="primary-cell"><strong>{r.title}</strong><span>{r.provider}</span></div>},{key:"member",label:"Mitglied",render:r=>`${r.first_name} ${r.last_name}`},{key:"starts_at",label:"Zeitraum",render:r=><>{dateOnly(r.starts_at)} – {dateOnly(r.ends_at)}</>},{key:"cost_cents",label:"Kosten",render:r=>euro(r.cost_cents)},{key:"status",label:"Status",render:r=><Status value={r.status}/>} ]}/>}

export function AuditPage(){const {items,loading,error}=useList("/audit"),[selected,setSelected]=useState<Row|null>(null);const columns:Column[]=useMemo(()=>[{key:"created_at",label:"Zeit",render:r=>dateTime(r.created_at)},{key:"user",label:"Benutzer",render:r=>r.first_name?`${r.first_name} ${r.last_name}`:"System"},{key:"action",label:"Aktion",render:r=><Status value={r.action}/>},{key:"entity_type",label:"Objekt",render:r=><span>{label(r.entity_type)} <code>{String(r.entity_id||"").slice(0,8)}</code></span>},{key:"ip_address",label:"IP-Adresse"}],[]);return <><PageHeader eyebrow="Nachvollziehbarkeit" title="Audit-Protokoll" description="Unveränderliche Übersicht sicherheits- und fachlich relevanter Aktionen."/><Panel>{error&&<ErrorBox message={error}/>} {loading?<Spinner/>:<DataTable items={items} columns={columns} onRowClick={setSelected}/>}</Panel><Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?`${label(selected.action)} · ${label(selected.entity_type)}`:"Audit-Eintrag"} eyebrow="Revisionsprotokoll"><div className="detail-hero"><ShieldCheck/><Status value={selected?.action}/></div><section className="detail-section"><div className="detail-grid"><div className="detail-field"><span>Zeitpunkt</span><strong>{dateTime(selected?.created_at)}</strong></div><div className="detail-field"><span>Benutzer</span><strong>{selected?.first_name?`${selected.first_name} ${selected.last_name}`:"System"}</strong></div><div className="detail-field"><span>Objekttyp</span><strong>{label(selected?.entity_type)}</strong></div><div className="detail-field"><span>Objekt-ID</span><strong className="mono">{selected?.entity_id||"—"}</strong></div><div className="detail-field"><span>IP-Adresse</span><strong>{selected?.ip_address||"—"}</strong></div><div className="detail-field wide"><span>Metadaten</span><strong className="mono">{selected?.metadata?JSON.stringify(JSON.parse(String(selected.metadata)),null,2):"{}"}</strong></div></div></section></Drawer></>}
