import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CheckSquare, Link2, Plus, Trash2, Workflow } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../AuthContext";
import { api, post, type Row } from "../api";
import { label, Status } from "./Status";
import { Button, EntityForm, ErrorBox, Modal, type FieldDef, useList } from "./UI";

export type EntityType="case"|"task"|"inquiry"|"agreement"|"decision"|"document"|"meeting"|"training"|"member"|"committee";
const typeOptions:{value:EntityType;label:string}[]=[
  {value:"case",label:"Vorgang"},{value:"task",label:"Aufgabe"},{value:"inquiry",label:"Mitarbeiteranfrage"},{value:"agreement",label:"Vereinbarung"},{value:"decision",label:"Beschluss"},{value:"document",label:"Dokument"},{value:"meeting",label:"Sitzung"},{value:"training",label:"Seminar"},{value:"member",label:"Mitglied"},{value:"committee",label:"Gremium / Ausschuss"},
];

function LinkForm({sourceType,sourceId,onDone}:{sourceType:EntityType;sourceId:string;onDone:()=>Promise<void>}){
  const [targetType,setTargetType]=useState<EntityType>(sourceType==="case"?"document":"case"),[query,setQuery]=useState(""),[options,setOptions]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{api<{items:Row[]}>(`/connections/options/${targetType}?q=${encodeURIComponent(query)}`).then(data=>{setOptions(data.items.filter(item=>!(targetType===sourceType&&item.id===sourceId)));setError("");}).catch(reason=>setError(reason instanceof Error?reason.message:"Auswahl konnte nicht geladen werden."));},200);return()=>window.clearTimeout(timer);},[query,sourceId,sourceType,targetType]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{await post("/connections",{sourceType,sourceId,targetType,targetId:form.get("targetId"),relation:form.get("relation")});await onDone();}catch(reason){setError(reason instanceof Error?reason.message:"Verknüpfung konnte nicht angelegt werden.");setBusy(false);}};
  return <form className="entity-form" onSubmit={submit}>{error&&<ErrorBox message={error}/>}<div className="form-grid"><label><span>Modul</span><select value={targetType} onChange={event=>{setTargetType(event.target.value as EntityType);setQuery("");setOptions([]);}}>{typeOptions.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label><span>Datensatz suchen</span><input value={query} onChange={event=>{setQuery(event.target.value);setOptions([]);}} placeholder="Titel oder Aktenzeichen"/></label><label className="span-2"><span>Datensatz *</span><select name="targetId" required defaultValue="" key={`${targetType}-${query}`}><option value="">{options.length?"Bitte wählen":"Keine Treffer"}</option>{options.map(option=><option value={String(option.id)} key={String(option.id)}>{option.reference&&`${option.reference} · `}{option.title}</option>)}</select></label><label className="span-2"><span>Art der Beziehung *</span><input name="relation" required defaultValue="Thematischer Zusammenhang" placeholder="z. B. Grundlage, Folgemaßnahme, Anlage"/></label></div><footer className="form-actions"><Button type="submit" disabled={busy} icon={<Link2/>}>{busy?"Verknüpft …":"Verknüpfung speichern"}</Button></footer></form>;
}

export function ConnectionsPanel({entityType,entityId,className=""}:{entityType:EntityType;entityId:string;className?:string}){
  const {permissions}=useAuth(),members=useList("/members"),[items,setItems]=useState<Row[]>([]),[error,setError]=useState(""),[linkOpen,setLinkOpen]=useState(false),[taskOpen,setTaskOpen]=useState(false),canLink=permissions?.includes("links:write"),canTask=entityType!=="task"&&permissions?.includes("tasks:write");
  const load=useCallback(async()=>{try{const data=await api<{items:Row[]}>(`/connections/${entityType}/${entityId}`);setItems(data.items);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Verknüpfungen konnten nicht geladen werden.");}},[entityId,entityType]);
  useEffect(()=>{void load();},[load]);
  const taskFields:FieldDef[]=[{key:"title",label:"Aufgabe",required:true,span:2},{key:"description",label:"Arbeitsauftrag",type:"textarea",span:2},{key:"assignedTo",label:"Zuständig",type:"select",options:members.items.filter(member=>member.active).map(member=>({value:String(member.id),label:`${member.first_name} ${member.last_name}`}))},{key:"dueAt",label:"Fällig am",type:"datetime-local"},{key:"priority",label:"Priorität",type:"select",defaultValue:"normal",options:["niedrig","normal","hoch","kritisch"].map(value=>({value,label:label(value)}))}];
  return <><section className={`detail-section connections-panel ${className}`}><header><div><h3>Verknüpfte Arbeit</h3><small>{items.length} modulübergreifende Beziehungen</small></div>{(canTask||canLink)&&<div className="connection-actions">{canTask&&<Button variant="ghost" onClick={()=>setTaskOpen(true)} icon={<CheckSquare/>}>Folgeaufgabe</Button>}{canLink&&<Button variant="ghost" onClick={()=>setLinkOpen(true)} icon={<Plus/>}>Verknüpfen</Button>}</div>}</header>{error&&<div className="connection-error"><ErrorBox message={error}/></div>}<div className="connection-list">{items.map(item=><div className="connection-card" key={String(item.connectionId)}><Link to={String(item.url)}><span className="connection-icon"><Workflow/></span><div><small>{item.typeLabel} · {item.relation}</small><strong>{item.reference&&`${item.reference} · `}{item.title}</strong></div><Status value={item.status}/></Link>{canLink&&<button className="icon-button" title="Verknüpfung lösen" onClick={async()=>{try{await api(`/connections/${item.connectionId}`,{method:"DELETE"});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Verknüpfung konnte nicht gelöst werden.");}}}><Trash2/></button>}</div>)}{!items.length&&!error&&<div className="connection-empty"><Link2/><div><strong>Noch nicht modulübergreifend verknüpft</strong><span>Ordnen Sie Zusammenhänge zu oder erzeugen Sie direkt eine Folgeaufgabe.</span></div></div>}</div></section><Modal title="Datensatz verknüpfen" open={linkOpen} onClose={()=>setLinkOpen(false)} wide><LinkForm sourceType={entityType} sourceId={entityId} onDone={async()=>{setLinkOpen(false);await load();}}/></Modal><Modal title="Folgeaufgabe aus diesem Kontext" open={taskOpen} onClose={()=>setTaskOpen(false)} wide><EntityForm fields={taskFields} submitLabel="Folgeaufgabe anlegen" onSubmit={async values=>{await post(`/connections/${entityType}/${entityId}/tasks`,values);setTaskOpen(false);await load();}}/></Modal></>;
}
