import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { AlertCircle, CheckCircle2, ChevronDown, LoaderCircle, Plus, Search, X } from "lucide-react";
import { api, type Row } from "../api";

export function Button({children,variant="primary",icon,onClick,type="button",disabled=false}:{children:ReactNode;variant?:"primary"|"secondary"|"ghost"|"danger";icon?:ReactNode;onClick?:()=>void;type?:"button"|"submit";disabled?:boolean}){return <button className={`button ${variant}`} onClick={onClick} type={type} disabled={disabled}>{icon}{children}</button>}
export function Badge({children,tone}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone||String(children).toLowerCase().replaceAll(" ","-")}`}>{children}</span>}
export function Empty({title="Noch keine Einträge",children}:{title?:string;children?:ReactNode}){return <div className="empty"><div className="empty-icon"><CheckCircle2/></div><h3>{title}</h3>{children&&<p>{children}</p>}</div>}
export function Spinner(){return <div className="loading"><LoaderCircle className="spin"/> Daten werden geladen …</div>}
export function ErrorBox({message}:{message:string}){return <div className="error-box"><AlertCircle/>{message}</div>}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div>{action}</div>}</header>}
export function Panel({title,action,children,className=""}:{title?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{(title||action)&&<header className="panel-head">{title&&<h2>{title}</h2>}{action}</header>}{children}</section>}

export function Modal({title,open,onClose,children,wide=false}:{title:string;open:boolean;onClose:()=>void;children:ReactNode;wide?:boolean}){
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};if(open)document.addEventListener("keydown",fn);return()=>document.removeEventListener("keydown",fn);},[open,onClose]);
  if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose();}}><div className={`modal ${wide?"wide":""}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Schließen"><X/></button></header>{children}</div></div>;
}

export interface FieldDef{key:string;label:string;type?:"text"|"textarea"|"date"|"datetime-local"|"select"|"number"|"checkbox"|"email"|"password";required?:boolean;placeholder?:string;options?:{value:string;label:string}[];span?:2;defaultValue?:string|number|boolean;min?:number;step?:number}
export function EntityForm({fields,onSubmit,submitLabel="Speichern",initial={}}:{fields:FieldDef[];onSubmit:(data:Record<string,unknown>)=>Promise<void>;submitLabel?:string;initial?:Record<string,unknown>}){
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget),data:Record<string,unknown>={};for(const field of fields){const value=fd.get(field.key);data[field.key]=field.type==="checkbox"?value==="on":field.type==="number"&&value!==""?Number(value):value||null;}try{await onSubmit(data);}catch(err){setError(err instanceof Error?err.message:"Speichern fehlgeschlagen.");setBusy(false);}};
  return <form onSubmit={submit} className="entity-form">{error&&<ErrorBox message={error}/>}<div className="form-grid">{fields.map(field=><label className={field.span===2?"span-2":""} key={field.key}><span>{field.label}{field.required&&" *"}</span>{field.type==="textarea"?<textarea name={field.key} required={field.required} placeholder={field.placeholder} defaultValue={String(initial[field.key]??field.defaultValue??"")}/>:field.type==="select"?<div className="select-wrap"><select name={field.key} required={field.required} defaultValue={String(initial[field.key]??field.defaultValue??"")}><option value="">Bitte wählen</option>{field.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select><ChevronDown/></div>:field.type==="checkbox"?<input type="checkbox" name={field.key} defaultChecked={Boolean(initial[field.key]??field.defaultValue)}/>:<input type={field.type||"text"} name={field.key} required={field.required} placeholder={field.placeholder} min={field.min} step={field.step} defaultValue={String(initial[field.key]??field.defaultValue??"")}/>}</label>)}</div><footer className="form-actions"><Button type="submit" disabled={busy} icon={busy?<LoaderCircle className="spin"/>:<CheckCircle2/>}>{busy?"Speichert …":submitLabel}</Button></footer></form>;
}

export function useList(url:string){const [items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const reload=useCallback(async()=>{setLoading(true);try{const data=await api<{items:Row[]}>(url);setItems(data.items);setError("");}catch(e){setError(e instanceof Error?e.message:"Laden fehlgeschlagen.");}finally{setLoading(false);}},[url]);useEffect(()=>{void reload();},[reload]);return{items,loading,error,reload};}

export interface Column{key:string;label:string;render?:(row:Row)=>ReactNode;className?:string}
export function DataTable({items,columns,onRowClick}:{items:Row[];columns:Column[];onRowClick?:(row:Row)=>void}){const [query,setQuery]=useState("");const filtered=items.filter(item=>Object.values(item).some(value=>String(value??"").toLowerCase().includes(query.toLowerCase())));return <><div className="table-tools"><div className="search-input"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Liste durchsuchen …"/></div><span>{filtered.length} Einträge</span></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th className={c.className} key={c.key}>{c.label}</th>)}</tr></thead><tbody>{filtered.map((row,index)=><tr key={String(row.id??index)} onClick={()=>onRowClick?.(row)} className={onRowClick?"clickable":""}>{columns.map(c=><td className={c.className} key={c.key}>{c.render?c.render(row):String(row[c.key]??"—")}</td>)}</tr>)}</tbody></table></div>{!filtered.length&&<Empty title={query?"Keine Treffer":"Noch keine Einträge"}/>}</>}

export function NewButton({onClick,label="Neu anlegen"}:{onClick:()=>void;label?:string}){return <Button onClick={onClick} icon={<Plus/>}>{label}</Button>}
